config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
  	collection do 
  		get :import
  		get :table, path: 'table(/:search)(/:page)(/:sort_column)(/:sort_style)'
			post :csv_import
  	end
  end

  root 'users#import'
end

app/models/affiliation.rb
class Affiliation < ApplicationRecord
  has_many :user_affiliations, dependent: :destroy
  has_many :users, through: :user_affiliations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :user_locations, dependent: :destroy
  has_many :users, through: :user_locations
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_affiliations, dependent: :destroy
  has_many :affiliations, through: :user_affiliations
  has_many :user_locations, dependent: :destroy
  has_many :locations, through: :user_locations

  validates :first_name, presence:true
  validates :gender, presence: true
  validates :species, presence: true

	def self.import_csv(csv_data)
		CSV.foreach(csv_data, headers: true, :row_sep => :auto) do |data|
      user = data.to_hash
      if user["Affiliations"].blank?
        next
      else

      	user_name = User.split_name(user["Name"])

        csv_user = User.create(
          first_name: user_name[:first_name],
          last_name: user_name[:last_name],
          species: user["Species"],
          gender: user["Gender"],
          weapon: user["Weapon"],
          vehicle: user["Vehicle"]
        )

        User.save_location(user["Location"], csv_user)
        User.save_affiliation(user["Affiliations"], csv_user)
      end
	  end
	end

	def self.split_name(name)
    split_name = name.split(" ")
    if split_name.size > 2
      first_name = split_name[0].capitalize
      for i in 1..(split_name.size-2)
        first_name = first_name + " #{split_name[i].capitalize}"
      end
      last_name = split_name.last.capitalize
    elsif split_name.size == 1
      first_name = split_name[0].capitalize
      last_name = ""
    else
      first_name = split_name[0].capitalize
      last_name = split_name.last.capitalize
    end
		
    user_name = {
			first_name: first_name,
			last_name: last_name
    }

    return user_name
	end

	def self.save_location(csv_location, user)
    if Location.exists?(title: csv_location)
      location = Location.find_by(title: csv_location.titlecase)
    else
      location = Location.create(title: csv_location.titlecase)
    end
		
    user.locations << location
	end

	def self.save_affiliation(csv_affiliation, user)
    if Affiliation.exists?(title: csv_affiliation)
      affiliation = Affiliation.find_by(title: csv_affiliation)
    else
      affiliation = Affiliation.create(title: csv_affiliation)
    end

    user.affiliations << affiliation
	end

  def full_name
    self.first_name + ' ' + self.last_name
  end

  def self.search(search_data)
    where(['first_name ilike :query',
      'last_name ilike :query',
      'species ilike :query',
      'gender ilike :query',
      'weapon ilike :query',
      'vehicle ilike :query',
      'affiliations.title ilike :query',
      'locations.title ilike :query'].join(' OR '), {query: "%#{search_data}%" }
    ).references(:affiliations, :locations)
  end
end

app/models/user_affiliation.rb
class UserAffiliation < ApplicationRecord
  belongs_to :user
  belongs_to :affiliation
end

app/models/user_location.rb
class UserLocation < ApplicationRecord
  belongs_to :user
  belongs_to :location
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def import
	end

	def table
		users_all = User.all.includes(:locations, :affiliations)

		# checks if the params exists for the page.
		if (params.keys & ["search", "page", "sort_column", "sort_style"]).any?
			@users = load_users(users_all)
		else
			@current_page = 1
			@max_page = (users_all.length.to_f/10).ceil
			@users = users_all.limit(10)

			@users = mapping_data(@users)
		end

		# have the prev button display or not
		@prev_btn_display = !params[:page].blank? && params[:page].to_i != 1 && params[:page] != "nil"
		# have the next button display or not
		@next_btn_display = params[:page].to_i != @max_page
	end

	def csv_import
    if params[:file]
    	# imports the data from csv using the user model method.
    	User.import_csv(params[:file].path)
		end

    redirect_to url_for(controller: :users, action: :import)
    return
	end

	def load_users(users_all)
		if params[:search] != "nil"
			# Search the users data with mutli column searchs.
			users_all = users_all.search(params[:search])
		end
		# maps the user data into hash
		users_all = mapping_data(users_all)
		if params[:sort_column] != "nil" && params[:sort_style] != "nil"
			if params[:sort_style] == "asc"
				users_all = users_all.sort_by{ |k| k["#{params[:sort_column]}"] }
			else
				users_all = users_all.sort_by{ |k| k["#{params[:sort_column]}"] }.reverse!
			end
		end
		if params[:page] != "nil"
			# set current page for the pagination
			@current_page = params[:page].to_i
			# set max page for the pagination
			@max_page = (users_all.length.to_f/10).ceil
			start_num = 10*(@current_page-1)
			end_num = 10*@current_page
			# limits the data to only display max of 10 items depending on the start and end num
			users_all = users_all[start_num, end_num]
		else
			# set current page for the pagination
			@current_page = 1
			# set max page for the pagination
			@max_page = (users_all.length.to_f/10).ceil
			# limits the data to only display max of 10 items
			users_all = users_all[0, 10]
		end

		return users_all
	end

	def mapping_data(users)
		users_hash = users.map { |e| {
			"full_name" => e.full_name,
			"location" => e.locations.pluck(:title).join(", "),
			"species" => e.species,
			"gender" => e.gender,
			"affiliations" => e.affiliations.pluck(:title).join(", "),
			"weapon" => e.weapon,
			"vehicle" => e.vehicle
		}}
		return users_hash
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SterningCodingTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :css_area %>
  </head>

  <body>
    <%= yield %>
    <%= yield :js_area %>
  </body>
</html>

app/views/users/import.html.erb
<%= content_for :js_area do %>
  <script>
    $('#inputGroupFile01').on('change', function(){
      if($('#inputGroupFile01').val() != ""){
        var file_name_array = $('#inputGroupFile01').val().split('\\');
        var file_name = file_name_array[file_name_array.length-1]
        $('#inputGroupFileLabel').text(file_name);
      }else{
        $('#inputGroupFileLabel').text("Choose file");
      }
    });
  </script>
<% end %>

<div class="container mt-4" id="app">
  <div class="row">
    <div class="col-12">
      <h1>Import Data</h1>
    </div>
    <div class="col-12 mt-4">
      <%= form_tag csv_import_users_path, multipart: true do %>
        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <span class="input-group-text">Upload</span>
          </div>
          <div class="custom-file">
            <%= file_field_tag :file, class: "custom-file-input", id: "inputGroupFile01" %>
            <label class="custom-file-label" for="inputGroupFile01" id="inputGroupFileLabel">Choose file</label>
          </div>
        </div>
        <%= submit_tag "Import CSV", class: "btn btn-primary" %>
      <% end %>
    </div>

    <% if User.any? %>
      <div class="col-12 mt-4">
        <%= link_to "Vue Table", table_users_path, class: 'btn btn-success text-white' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/table.html.erb
<%= content_for :js_area do %>
  <script>
    var vueapp = new Vue({
      el: '#app',
      data: {
        search: "<%= params[:search].blank? ? "nil" : params[:search] %>",
        page: "<%= params[:page].blank? ? "nil" : params[:page] %>",
        sort_column: "<%= params[:sort_column].blank? ? "nil" : params[:sort_column] %>",
        sort_style: "<%= params[:sort_style].blank? ? "nil" : params[:sort_style] %>"
      },
      mounted: function(){
        if (this.search != "nil") {
          $('#search_text').val(this.search)
        }
      },
      methods: {
        page_number_click: function(page_num){
          this.page = page_num;
          this.change_page_params();
        },
        search_text_fnc: function(){
          if ($('#search_text').val() != '') {
            this.search = $('#search_text').val();
          }else{
            this.search = "nil";
          }
          this.change_page_params();
        },
        sort_column_fnc: function(column_name){
          if (column_name != this.sort_column) {
            this.sort_style = 'asc';
          }else{
            if (this.sort_style == 'nil'|| this.sort_style == 'desc') {
              this.sort_style = 'asc';
            } else if (this.sort_style == 'asc') {
              this.sort_style = 'desc';
            }
          }
          this.sort_column = column_name;
          this.change_page_params();
        },
        change_page_params: function(){
          window.location.href = "<%= url_for(controller: :users, action: :table) %>/"+this.search+"/"+this.page+"/"+this.sort_column+"/"+this.sort_style+"/"
        }
      }
    });
  </script>
<% end %>

<%= content_for :css_area do %>
  <style>
    .buttons {
      cursor: pointer;
    }
  </style>
<% end %>

<div class="container mt-4" id="app">
  <div class="row">
    <div class="col-12">
      <h1>Import Data</h1>
    </div>
    <div class="col-12 mt-1">
      <div class="row">
        <div class="col-4"></div>
        <div class="col-4"></div>
        <div class="col-4">
          <div class="input-group mb-3">
            <input type="text" id="search_text" class="form-control" aria-label="Search" aria-describedby="button-addon2">
            <div class="input-group-append">
              <button class="btn btn-outline-secondary" type="button" id="button-addon2" v-on:click="search_text_fnc" >Search</button>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-12 mt-4">
      <table class="table table-hover">
        <thead>
          <th class="buttons" v-on:click="sort_column_fnc('name')">Name</th>
          <th class="buttons" v-on:click="sort_column_fnc('location')">Location</th>
          <th class="buttons" v-on:click="sort_column_fnc('species')">Species</th>
          <th class="buttons" v-on:click="sort_column_fnc('gender')">Gender</th>
          <th class="buttons" v-on:click="sort_column_fnc('affiliations')">Affiliations</th>
          <th class="buttons" v-on:click="sort_column_fnc('weapon')">Weapon</th>
          <th class="buttons" v-on:click="sort_column_fnc('vehicle')">Vehicle</th>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user["full_name"] %></td>
              <td><%= user["location"] %></td>
              <td><%= user["species"] %></td>
              <td><%= user["gender"] %></td>
              <td><%= user["affiliations"] %></td>
              <td><%= user["weapon"] %></td>
              <td><%= user["vehicle"] %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-12 mt-1">
      <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
          <% if @prev_btn_display %>
            <li class="page-item"><a class="page-link" href="#" v-on:click="page_number_click(<%= @current_page-1 %>)">Previous</a></li>
          <% end %>
          <% for i in 1..@max_page %>
            <li class="page-item <%= @current_page == i ? 'active' : '' %>"><a class="page-link" href="#" v-on:click="page_number_click(<%= i %>)"><%= i %></a></li>
          <% end %>
          <% if @next_btn_display %>
            <li class="page-item"><a class="page-link" href="#" v-on:click="page_number_click(<%= @current_page+1 %>)">Next</a></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</div>